-- 01_db_setup_presencialidad.sql
-- FIX_SQL_VIEW_INDEXES_PRESENCIALIDAD_20260602
-- Ejecutar en PostgreSQL. Esquema: sales.

CREATE SCHEMA IF NOT EXISTS sales;

-- Vista estándar para que la app no dependa de nombres largos del ETL.
CREATE OR REPLACE VIEW sales.vw_colaboradores_presencialidad AS
SELECT
    id,
    CAST(dni AS VARCHAR(20)) AS dni,
    TRIM(CONCAT_WS(' ', nombres, apellido_paterno, apellido_materno)) AS nombre,
    razon_social,
    canal,
    sub_canal,
    region,
    departamento,
    provincia,
    supervisor_a_cargo AS supervisor,
    dni_supervisor,
    coordinador,
    dni_coordinador,
    cargo_rol,
    estado,
    fecha_de_creacion_usuario AS fecha_alta,
    fecha_de_cese AS fecha_cese,
    motivo,
    zona_1,
    fecha_actualizacion
FROM sales.ventas_unificada;

-- Tabla de asistencia, si aún no existe.
CREATE TABLE IF NOT EXISTS sales.asistencia_presencialidad (
    id_asistencia BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dni VARCHAR(20) NOT NULL,
    periodo VARCHAR(7) NOT NULL,
    dia INT NOT NULL,
    columna_dia VARCHAR(20),
    marca VARCHAR(20) NOT NULL,
    razon_social VARCHAR(150),
    supervisor VARCHAR(200),
    coordinador VARCHAR(200),
    departamento VARCHAR(100),
    provincia VARCHAR(100),
    usuario_registro VARCHAR(100),
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    usuario_actualizacion VARCHAR(100),
    fecha_actualizacion TIMESTAMP,
    CONSTRAINT uq_asistencia_dni_periodo_dia UNIQUE (dni, periodo, dia)
);

-- Tabla de sustentos A-BM, si aún no existe.
CREATE TABLE IF NOT EXISTS sales.sustentos_bajas_medicas (
    id_sustento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    periodo VARCHAR(7) NOT NULL,
    dia INT NOT NULL,
    columna_dia VARCHAR(20),
    fecha_asistencia DATE,
    dni VARCHAR(20) NOT NULL,
    nombre VARCHAR(250),
    razon_social VARCHAR(150),
    motivo VARCHAR(50) NOT NULL,
    nombre_archivo VARCHAR(250),
    link_documento TEXT,
    usuario_registro VARCHAR(100),
    fecha_subida TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Índices para que no se congele al filtrar.
CREATE INDEX IF NOT EXISTS idx_vu_pres_razon_estado
ON sales.ventas_unificada (razon_social, estado);

CREATE INDEX IF NOT EXISTS idx_vu_pres_dni
ON sales.ventas_unificada (dni);

CREATE INDEX IF NOT EXISTS idx_vu_pres_filtros
ON sales.ventas_unificada (razon_social, estado, departamento, provincia);

CREATE INDEX IF NOT EXISTS idx_asistencia_periodo_dia_dni
ON sales.asistencia_presencialidad (periodo, dia, dni);

CREATE INDEX IF NOT EXISTS idx_asistencia_razon_periodo_dia
ON sales.asistencia_presencialidad (razon_social, periodo, dia);

CREATE INDEX IF NOT EXISTS idx_sustentos_dni_periodo_dia
ON sales.sustentos_bajas_medicas (dni, periodo, dia);

-- Validación rápida.
SELECT table_schema, table_name
FROM information_schema.tables
WHERE table_schema = 'sales'
  AND table_name IN ('ventas_unificada', 'asistencia_presencialidad', 'sustentos_bajas_medicas');
