[server]
headless = true
fileWatcherType = "none"
runOnSave = false
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200
maxMessageSize = 200

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
showErrorDetails = false

[runner]
fastReruns = true
magicEnabled = false
